# Base configuration for site
---
baseurl: 'http://localhost/'
title: 'matthewemes.com'
defaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: en
# yamllint disable-line rule:line-length
copyright: Copyright © 2017-2023 Matthew Emes.<br/><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
ignoreFiles:
  - \.DS_Store$
