---
main:
  - identifier: categories
    url: /categories/
    name: Categories
    weight: 10
  - identifier: series
    url: /series/
    name: Series
    weight: 20
  - identifier: tags
    url: /tags/
    name: Tags
    weight: 30
  - identifier: about
    url: /about/
    name: About
    weight: 40
