---
imports:
  - path: github.com/schnerring/hugo-theme-gruvbox
  - path: github.com/schnerring/hugo-mod-json-resume
    mounts:
      - source: data
        target: data
      - source: layouts
        target: layouts
      - source: assets/css/json-resume.css
        target: assets/css/critical/44-json-resume.css
mounts:
  - source: node_modules/simple-icons/icons
    target: assets/simple-icons
  - source: assets
    target: assets
  - source: layouts
    target: layouts
  - source: static
    target: static
  - source: node_modules/prismjs
    target: assets/prismjs
  - source: node_modules/prism-themes/themes
    target: assets/prism-themes
  - source: node_modules/typeface-fira-code/files
    target: static/fonts
  - source: node_modules/typeface-roboto-slab/files
    target: static/fonts
  - source: node_modules/@tabler/icons/icons
    target: assets/tabler-icons
