baseurl = "/"
languageCode = "en"
title = "Matthew Emes"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-22915022-1"
copyright = "Copyright © 2017 Matthew Emes. Except where explicitlty noted, content on this site is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (see https://creativecommons.org/licenses/by-sa/4.0/)."

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
    
[author]
    name = "Matthew Emes"

[params]
    name = "Matthew Emes"
    bio = "Philomath | Cloud Architect | Open Source Advocate"
    copyright = "Copyright © 2017 Matthew Emes. Except where explicitlty noted, content on this site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](//creativecommons.org/licenses/by-sa/4.0/)."
    twitter = "matthewemes"
    enableRSS = true
    iconFont = "font-awesome"

[social]
    twitter = "https://twitter.com/matthewemes"
    github = "https://github.com/memes"
#    bitbucket = "//bitbucket.org/memes"
    facebook = "https://facebook.com/matthewemes"
    google-plus = "https://plus.google.com/+matthewemes"
    linkedin = "https://www.linkedin.com/in/matthewemes"