# yamllint disable rule:line-length
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: install talisman
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: thoughtworks/talisman
          extension-matching: disable
          rename-to: talisman
          chmod: 0755
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
