# On push to main, rebuild and redeploy site
# spell-checker: disable
---
name: publish site
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy matthewemes.com site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.121.1'
          extended: true
      - name: Install npm packages
        run: npm ci
      - name: Build Site
        run: hugo --minify --logLevel info --environment production
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: memes/memes.github.io
          publish_branch: main
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
